const { sign } = modules.jsonwebtoken;
const token = sign({username: 'jwt-user'}, 'superSecret');

result.data = `
<script>
    const url = 'https://p9:8081/user/logon/jwt/simple-jwt';
    fetch(url, {method: 'POST', headers: {Authorization: 'Bearer ${token}'}}).then(result => window.location.href = "https://p9:8081/cockpit");
</script>`;

result.statusCode = 200;
result.contentType = 'text/html';

